// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXge58i9cPrtFuDB9Kf6KNdZ-kTtQvNTI',
    appId: '1:141570028049:web:f5c206691965b0e7a6b7b0',
    messagingSenderId: '141570028049',
    projectId: 'spotifyclone-ff069',
    authDomain: 'spotifyclone-ff069.firebaseapp.com',
    storageBucket: 'spotifyclone-ff069.appspot.com',
    measurementId: 'G-QS5RPVD2M6',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXge58i9cPrtFuDB9Kf6KNdZ-kTtQvNTI',
    appId: '1:141570028049:web:f5c206691965b0e7a6b7b0',
    messagingSenderId: '141570028049',
    projectId: 'spotifyclone-ff069',
    authDomain: 'spotifyclone-ff069.firebaseapp.com',
    storageBucket: 'spotifyclone-ff069.appspot.com',
    measurementId: 'G-QS5RPVD2M6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrbl-ng6R4E8lJSUkMHOVPDZx6NGddkco',
    appId: '1:141570028049:ios:5697848d5fae7d8ca6b7b0',
    messagingSenderId: '141570028049',
    projectId: 'spotifyclone-ff069',
    storageBucket: 'spotifyclone-ff069.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrbl-ng6R4E8lJSUkMHOVPDZx6NGddkco',
    appId: '1:141570028049:ios:5697848d5fae7d8ca6b7b0',
    messagingSenderId: '141570028049',
    projectId: 'spotifyclone-ff069',
    storageBucket: 'spotifyclone-ff069.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTog7LsNQnISFKbfkN_egohmKTCW4hs-8',
    appId: '1:141570028049:android:3ecf0a3254333e37a6b7b0',
    messagingSenderId: '141570028049',
    projectId: 'spotifyclone-ff069',
    storageBucket: 'spotifyclone-ff069.appspot.com',
  );

}